apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv-1
  namespace: monitoring
  labels:
    usage: prometheus
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.56.100
    path: "/var/nfs/prometheus-1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv-2
  namespace: monitoring
  labels:
    usage: prometheus
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.56.100
    path: "/var/nfs/prometheus-2"
