apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
  selector:
    app: wordpress
    tier: nginx
---
apiVersion: apps/v1 # for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: nginx
  template:
    metadata:
      labels:
        app: wordpress
        tier: nginx
    spec:
      containers:
      - image: misbahulard/nginx
        name: nginx
        ports:
        - containerPort: 80
          name: nginx
        - containerPort: 443
          name: nginx-tls
        volumeMounts:
        - name: nginx-persistent-storage
          mountPath: /var/www/html/wp-content
        - name: nginx-secret
          mountPath: /etc/nginx/tls
        - name: nginx-configmap
          mountPath: /etc/nginx/conf.d
        env:
          - name: PHP_HOST
            value: phpfpm
          - name: DB_HOST
            value: mariadb
      volumes:
      - name: nginx-secret
        secret:
          secretName: nginx
      - name: nginx-configmap
        configMap:
          name: nginx-vh
      - name: nginx-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-pv-claim
