apiVersion: v1
kind: Service
metadata:
  name: phpfpm
  labels:
    app: phpfpm
spec:
  ports:
    - port: 9000
  selector:
    app: wordpress
    tier: phpfpm
---
apiVersion: apps/v1 # for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: phpfpm
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: phpfpm
  replicas: 2
  template:
    metadata:
      labels:
        app: wordpress
        tier: phpfpm
    spec:
      containers:
      - image: misbahulard/phpfpm
        name: phpfpm
        ports:
        - containerPort: 9000
          name: phpfpm
        volumeMounts:
        - name: phpfpm-persistent-storage
          mountPath: /var/www/html/wp-content
        env:
          - name: USE_REDIS
            value: "yes"
          - name: REDIS_HOST
            value: "redis-master"
          - name: DB_HOST
            value: mariadb
      volumes:
      - name: phpfpm-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-pv-claim
