apiVersion: v1 
kind: Service 
metadata: 
  name: redis-slave
  labels: 
    app: redis-slave
spec: 
  ports: 
    - port: 6379 
  selector: 
    app: wordpress 
    tier: redis-slave
--- 
apiVersion: apps/v1 # for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1 
kind: Deployment 
metadata: 
  name: redis-slave
  labels: 
    app: wordpress 
spec: 
  selector: 
    matchLabels: 
      app: wordpress 
      tier: redis-slave
  replicas: 2
  template: 
    metadata: 
      labels: 
        app: wordpress 
        tier: redis-slave 
    spec: 
      containers: 
      - image: misbahulard/redis-slave
        name: redis-slave
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports: 
        - containerPort: 6379 
          name: redis-slave
