route:
  group_by: [Alertname]
  receiver: email
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 5m

receivers:
- name: email
  email_configs:
  - to: misbahulard@gmail.com
    from: misbahulard@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "misbahulard@gmail.com"
    auth_identity: "misbahulard@gmail.com"
    auth_password: "tzvhvqhhsabxhdkj"
